server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: mercado-libre
          uri: https://api.mercadolibre.com
          filters:
            - name: GatewayCustomFilter
          predicates:
            - Path=/**