server:
  port: 8080
application:
  proxy:
    base-path: /proxy
    rejection-status: ${PROXY_REJECTED_STATUS:423}
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/proxy_service}
  cloud:
    gateway: # https://cloud.spring.io/spring-cloud-gateway/reference/html/#gateway-starter
      routes:
        - id: mercado-libre
          uri: ${API_URL:https://api.mercadolibre.com}
          predicates:
            - Path=${application.proxy.base-path}/**
          filters: # https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/gatewayfilter-factories.html
            - name: GatewayCustomFilter
            - StripPrefix=1
feign:
  proxy-persistence:
    url: ${PERSISTENCE_API_URL:localhost:8081}
