server:
  port: 8080
application:
  proxy:
    base-path: /proxy
    rejection-status: 423
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/proxy_service
  cloud:
    gateway: # https://cloud.spring.io/spring-cloud-gateway/reference/html/#gateway-starter
      routes:
        - id: mercado-libre
          uri: https://api.mercadolibre.com
          predicates:
            - Path=${application.proxy.base-path}/**
          filters: # https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/gatewayfilter-factories.html
            - name: GatewayCustomFilter
            - StripPrefix=1
feign:
  proxy-persistence:
    url: https://api.mercadolibre.com
