services:
  proxy-service:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/proxy_service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
